# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: "android"

steps:
  - label: "Code Freeze"
    plugins: [$CI_TOOLKIT]
    command: |
      .buildkite/commands/configure-git-for-release-management.sh

      install_gems

      bundle exec fastlane code_freeze skip_confirm:true
