# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---


steps:
  - label: "Complete Code Freeze"
    plugins: [$CI_TOOLKIT]
    command: |
      source .buildkite/commands/configure-git-for-release-management.sh
      .buildkite/commands/checkout-release-branch.sh

      install_gems

      bundle exec fastlane complete_code_freeze skip_confirm:true
    agents:
       queue: "tumblr-metal"
