# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---


steps:
  - label: "Finalize release"
    plugins: [$CI_TOOLKIT]
    command: |
      source use-bot-for-git

      .buildkite/commands/checkout-release-branch.sh

      install_gems

      cp gradle.properties-example gradle.properties

      bundle exec fastlane finalize_release skip_confirm:true
    agents:
       queue: "tumblr-metal"
