# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---


steps:
  - label: "New Beta Release"
    plugins: [$CI_TOOLKIT]
    command: |
      source use-bot-for-git

      install_gems

      cp gradle.properties-example gradle.properties

      bundle exec fastlane new_beta_release skip_confirm:true
    agents:
       queue: "tumblr-metal"
