# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---


steps:
  - label: "Update release notes"
    plugins: [$CI_TOOLKIT]
    command: |
      source use-bot-for-git

      .buildkite/commands/checkout-editorial-branch.sh

      install_gems

      bundle exec fastlane update_appstore_strings version:${RELEASE_VERSION}
    agents:
       queue: "tumblr-metal"
